# -*- coding: utf-8 -*-
"""task4_visuvalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMflVnDIyZcZi0E_bTgCr9a_zKmbkrh9
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("data/trends_cleaned.csv")

print("✅ Data Loaded")

category_counts = df["category"].value_counts()

plt.figure()
category_counts.plot(kind="bar")

plt.title("Number of Stories per Category")
plt.xlabel("Category")
plt.ylabel("Count")

plt.show()

avg_score = df.groupby("category")["score"].mean()

plt.figure()
avg_score.plot(kind="bar")

plt.title("Average Score per Category")
plt.xlabel("Category")
plt.ylabel("Average Score")

plt.show()

avg_comments = df.groupby("category")["num_comments"].mean()

plt.figure()
avg_comments.plot(kind="bar")

plt.title("Average Comments per Category")
plt.xlabel("Category")
plt.ylabel("Average Comments")

plt.show()

top10 = df.sort_values(by="score", ascending=False).head(10)

plt.figure()
plt.barh(top10["title"], top10["score"])

plt.title("Top 10 Stories by Score")
plt.xlabel("Score")
plt.ylabel("Title")

plt.show()