# -*- coding: utf-8 -*-
"""task3_analysic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6KFhGmuM1eta3B4Zvdm1pClOGXIs1lX
"""

import pandas as pd

df = pd.read_csv("data/trends_cleaned.csv")
print(df.head())

print(df.info())
print(df.describe())

import numpy as np

# Convert score column to numpy array
scores = np.array(df["score"])

print("Average score:", np.mean(scores))
print("Max score:", np.max(scores))
print("Min score:", np.min(scores))

category_counts = df["category"].value_counts()
print(category_counts)

avg_score = df.groupby("category")["score"].mean()
print(avg_score)

avg_comments = df.groupby("category")["num_comments"].mean()
print(avg_comments)

top_stories = df.sort_values(by="score", ascending=False).head(5)
print(top_stories[["title", "category", "score"]])

