# -*- coding: utf-8 -*-
"""task2processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcW2M5jwC7l9TQec1Vlfi-YJOwJGUUBF
"""

import pandas as pd
import json

# Load JSON file
file_path = "/content/data/trends_20260414.json"   # change date if needed

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Convert to DataFrame
df = pd.DataFrame(data)

# Check data
print(df.head())
print(df.info())

df

df['post_id']

df.drop_duplicates(subset=['post_id'])

df['author'].head(50)

df['author'].fillna('unknow')

df['num_comments']

df['num_comments'].fillna(0)

df

df['score']

df['score'].fillna(0)

df["author"].fillna("unknown")
df["num_comments"].fillna(0)
df["score"].fillna(0)

df["score"].astype(int)

df["num_comments"].astype(int)

df["title"].str.strip()

pd.to_datetime(df["collected_at"])

# Save cleaned data
output_file = "data/cleaned_trends.csv"
df.to_csv(output_file, index=False)

print(f"Cleaned data saved to {output_file}")