# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Pravallikakukunuri/44e5c9fcbc5ec0915ff20d1542f78eb3/task1_data_collection.ipynb
"""

import requests
import time
import os
import json
from datetime import datetime


TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {"User-Agent": "TrendPulse/1.0"}

# Categories and keywords
categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming"]
}

# Store results
collected_stories = []


# Step 1: Fetch Top Story IDs
try:
    response = requests.get(TOP_STORIES_URL, headers=headers)
    story_ids = response.json()[:500]  # first 500
except Exception as e:
    print("Error fetching top stories:", e)
    story_ids = []

# Step 2: Process by Category

for category, keywords in categories.items():
    print(f"\nProcessing category: {category}")

    count = 0

    for story_id in story_ids:
        if count >= 25:
            break

        try:
            res = requests.get(ITEM_URL.format(story_id), headers=headers)
            story = res.json()

            # Skip if no title
            if not story or "title" not in story:
                continue

            title = story["title"].lower()

            # Check keywords
            if any(keyword in title for keyword in keywords):

                data = {
                    "post_id": story.get("id"),
                    "title": story.get("title"),
                    "category": category,
                    "score": story.get("score", 0),
                    "num_comments": story.get("descendants", 0),
                    "author": story.get("by", "unknown"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }

                collected_stories.append(data)
                count += 1

        except Exception as e:
            print(f"Failed to fetch story {story_id}: {e}")
            continue

    # Wait 2 seconds AFTER each category
    time.sleep(2)


# Step 3: Save to JSON


# Create folder if not exists
if not os.path.exists("data"):
    os.makedirs("data")

# File name with date
file_name = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

# Save file
with open(file_name, "w", encoding="utf-8") as f:
    json.dump(collected_stories, f, indent=4)


# Final Output

print(f"\nCollected {len(collected_stories)} stories.")
print(f"Saved to {file_name}")

